version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: studyflow-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: studyflow_dev
    volumes:
      - mongodb_data:/data/db
    networks:
      - studyflow-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: studyflow-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - studyflow-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  studyflow-network:
    driver: bridge
